### ISSUE TITLE
Based on FTC Suggestion - Become familiar with VisionPortal APIs

### ISSUE THREAD

**Issue by rjain21** [metal-magic/FtcRobotController#29]
To quote there tweet _"On 7/11 FTC released the Offseason 8.2 version of the Software Development Kit (SDK). The SDK includes a new feature called the VisionPortal, which revolutionizes the way teams interact and program with Computer Vision (AprilTags & TensorFlow)."_

This is a hint that something related to Vision will be highly important - especially in Autonomous Mode

**Comment by adityakothari00** [comment]
https://ftc-docs.firstinspires.org/en/latest/apriltag/vision_portal/visionportal_overview/visionportal-overview.html

**Comment by rjain21** [comment]
The link is in the issue as well
